---
title: "关于进一步深化网校学生转化行为研究的建议"
author: "学科产品部"
date: "`r format(Sys.time(), '%Y.%m.%d')`"
output: 
  html_document:
    css: 
    theme: united
    highlight: kate
    toc: false
    toc_depth: 2
    toc_float: true
    number_sections: true
---

<script>
    window.oncontextmenu = function () {
        console.log("Right Click Disabled");
        return false;
    }
</script>
```{r setup, include=FALSE}
# default, cerulean, journal, flatly, darkly, readable, spacelab, united, cosmo, lumen, paper, sandstone, simplex, and yeti
#  default, tango, pygments, kate, monochrome, espresso, zenburn, haddock, breezedark, and textmate
knitr::opts_chunk$set(echo = TRUE)
#setwd("C:/Users/david/Documents/GitHub/lidaidavid.github.io/20191021 classes/")
library(tidyverse)
library(readxl)
library(plotly)
# library(extrafont)
Sys.setlocale("LC_CTYPE", "Chinese")
#font <- "STXihei"
#load("C:/0work/0tal/1 online_db/outputdata.RData")

#dir1 <- "C:/Users/david/Documents/GitHub/lidaidavid.github.io/20191021classes/"

#dir1 <- "https://lidaidavid.github.io/20191021classes/"

```

# 研究问题

## 哪些因素会影响学生的**转化**行为？

+ 学生的转化行为会受若干因素影响。网校近期对此问题进行了专项研究，对数据进行了描述统计。

+ 在此基础上，可以进一步采取**逻辑斯蒂回归**的方法，在**控制变量**的前提下，计算找出**影响转化行为的关键因素、并计算这些因素的影响程度**，从而为决策提供依据。


# 研究方法

## 逻辑斯蒂回归

**逻辑斯蒂回归**是指广义线性模型（GLM）中的逻辑斯蒂回归（logistic regression or logit model），用于研究的“哪些因素会影响一个事件发生与否的可能性”。“学生转化与否”就是一个典型的二分类变量，适合采用逻辑斯蒂回归进行分析。


## 其他方法
考虑到学生有生命周期、变量有多个层次、同班级之间可能会相互影响，还可以考虑生存分析（survival analysis）、层级模型（hierarchical model）和社会网络分析（social network analysis）等更加复杂的方法。这些方法可以在时间更加充裕的条件下进行探索。

## 为什么不采用机器学习模型

机器学习方法善于进行预测而非寻找因果关系。要解释转化行为受哪些因素影响、受这些因素多大影响不是典型的机器学习任务，更适合用社会科学研究方法进行研究。

# 模型构建

## 模型I：重辅导对学生转化是否有显著影响？

+ 根据业务伙伴的认知，提出假设：辅导老师的服务加重会对学生转化行为产生积极影响

    - 因变量：学生的转化行为。转化 = 新学员 且 上过优选课 且 续报下一季系统课程
 
    - 自变量：在优选课期间的辅导老师与其进行私聊的次数/文字长度/个性程度 + 是否进行过视频/音频一对一 + 在群运营中\@该学生的次数/文字长度/个性程度 + 给该学生发送物料总次数/个性程度
 
    - 控制变量：学生的城市（级别、人均gdp、区域） + 学生性别 + 学生年级 + 家庭经济状况 + 学生学习水平 + 报课学科 + 课程难度 + 教材版本 
    
## 模型II：辅导和主讲谁对转化的效应更大？

+ 上一个模型中没有控制主讲老师的相关变量，结论可能是不准确的。业务伙伴还会关心的问题：主讲和辅导谁对转化行为的影响更大？

+ 在保持前述模型不变的情况下，加入主讲相关的研究变量，就可以在控制了辅导老师的效应之余，测量主讲的影响。二者比较，就可以看出主讲和辅导谁的效果更大。

    - 增加变量：主讲素质（入职时长/课时费） + 是否在课程中与主讲互动过（被点名表扬etc）+ 主讲课上互动次数（时间） + 主讲与学生私下交流的次数

# 实施方案

1. 用SQL调取网校现有140万学生的个体数据，并根据研究需要进行初步数据清理和结构化。下面进行分析的数据是学生个体层面数据，对应着为其服务的主讲、辅导老师等人员。

2. 从全量数据中随机抽取1%的样本，形成测试数据，便于研究者在个人电脑上跑通数据分析的流程代码。

3. 根据学生对应的辅导老师，从辅导老师微信聊天记录库中调取这个老师和他的聊天记录（群中\@该学生的记录），并采用文本分析模型将老师与这个学生交流的次数、长度、个性化程度计算出来，再匹配给该学生。同理可以调取主讲老师的类似数据。

3. 利用Python对数据进行逻辑斯蒂回归模型的分析，检验各变量的影响，利用AIC、BIC等统计标准寻找最优模型。

4. 在技术专家协助下将优化的分析代码部署到服务器上，对全量数据进行分析，得出对转化行为受哪些因素影响、受多大影响的准确认知。

5. 由于上述过程都是通过代码实现的，完成之后可以直接常态化，每个季度对数据进行重复分析，监测变化。

# 输出结果

逻辑斯蒂回归模型输出的结果，可以解释**事件发生与否**受哪些因素影响、受这些因素多大影响。

逻辑斯蒂回归输出的是一组变量系数及其显著性。系数的正负，表示的是相应的因素对**转化**的影响是正的还是负的；系数的大小，表示相应因素对**转化**的影响幅度有多大；显著性表示这一关系有多可靠。

例如，一个简单的模型是：

$$ 转化 = \alpha * 主讲教龄 + \beta * 辅导私聊次数 + \epsilon$$
如果$\alpha$为正且显著，意味着主讲教龄越大转化发生的可能性就越大；$\beta$为正且显著，意味着辅导跟学生私聊次数越多转化发生的可能性越大。$\alpha$ 和 $\beta$ 都有确切的含义，表示**比数比的对数**(log odds ratio)，可以转化为类似“主讲教龄每增加一岁，学生转化行为发生的可能性增加$x\%$”这样的表述。

而且，上述模型还有一个含义是“在控制了变量的前提下”，也就是说，这里测量出的主讲教龄的影响是在这个学生接受辅导私聊次数一样多的情况下得到的结果，所以不会混淆主讲教龄和辅导私聊次数这两个变量的影响。

# 评估结论

+ 基于网校现有专项研究的初步结论，利用网校现有的存量数据，可以对研究问题进行初步分析，采用逻辑斯蒂回归模型取得初步的结果。研究方法可以适用到其他能够转化为是否问题的变量上，例如“是否续报”、“是否退费”、“是否扩科”等等。

+ 在对存量数据进行盘点、与技术专家进行咨询之前，难以判断研究投入的时间与资源规模。目前初步判断，如果研究团队有专人全职进行分析，数据资源到位，要花的时间在1个月到6个月之间。使用代码进行分析的好处是跑通之后可以常态化，每隔一段时间重新筛选数据重复分析，监测影响因素是否发生变化，而每季度的边际成本很低。

+ 总之，对网校存量数据进行初步的统计分析对理解用户需求、澄清转化机制、指导网校决策有重大价值，建议组建专家团队用社会科学方法开展研究。
    